version: '3.8'

services:
  backend:
    build: ./back-end
    ports:
      - "5000:5000"  
    volumes:
      - ./backend:/app
    networks:
      - app-network 
    depends_on:
      - db  

      
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apartments
      MYSQL_INITDB_SKIP_TZINFO: "true"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_EXTRA_FLAGS: "--innodb-force-recovery=1"
    ports:
      - "3300:3306" 
    networks:
      - app-network  


  frontend:
    build: ./front-end/apartments-app
    ports:
      - "3000:3000"  
    volumes:
      - ./frontend:/app
    depends_on:
      - backend  
    networks:
      - app-network  

networks:
  app-network: 
    driver: bridge  