version: '3.8'

services:
  backend:
    build: ./back-end
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    networks:
      - booknet

  frontend:
    build: ./front-end/apartments-app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - booknet

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apartments
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
networks:
  booknet: